### PR TITLE
Added fixes for Secret World Legends

### PR DESCRIPTION
**Pull request by zerodogg**
Needs some winetricks deps, as well as using builtin d3d9.

### CODE REVIEW

**Comment by zerodogg** [comment]
First one didn't work properly, as it overwrote WINEDLLOVERRIDES completely for some reason and thus disabled dxvk completely. This one keeps the original one.

**Comment by GloriousEggroll** [comment]
> Breaks with dxvk's d3d9 implementation.

This needs to be reported to upstream dxvk, otherwise it will be covered up by this workaround and never properly fixed:

http://github.com/doitsujin/dxvk

Other than that the _43 overrides are ok.

**Comment by Blisto91** [comment]
Is this just for the launcher or the ingame lighting/shadow issue? https://github.com/doitsujin/dxvk/issues/2418

**Comment by zerodogg** [comment]
@GloriousEggroll you're right, I'll try to get together a report upstream

@Blisto91 This fixes the launcher, which uses dx9. The game itself defaults to dx11 these days, which works great with dxvk (and does not have those lighting issues). With this hack the game is able to both patch and run by default.

**Comment by Blisto91** [comment]
I discovered a few days ago that the launcher can be worked around by setting `d3d9.shaderModel = 2` for it in the dxvk config.
I havn't made a PR since i wasn't sure if that indicated a issue with shaderModel 3 in dxvk and i should make a issue instead. But i haven't gotten feedback on that. I've tried asking again.

**Comment by GloriousEggroll** [comment]
I went ahead and merged and just removed the d3d9 override, fixed via patch directly for dxvk. will open a PR for dxvk soon

**Comment by Blisto91** [comment]
dxvk issue https://github.com/doitsujin/dxvk/issues/3116

**Pull request merged**
