### PR TITLE
Added fix for ATRI -My Dear Moments-

### PR DESCRIPTION
**Pull request by DevSplash**
Fix https://github.com/ValveSoftware/Proton/issues/5559#issuecomment-1058309456

### CODE REVIEW

**Comment by DevSplash** [comment]
> Do you mind describing the problem and explaining what exactly this patch aims to fix? Recent reports of [Protondb indicates that there is no problem.](https://www.protondb.com/app/1230140) While I see there's an open issue on Github for it, it is [outdated and may not be relevant anymore](https://github.com/ValveSoftware/Proton/issues/5559).
> 
> Since this is the case, I am against this PR as it adds nothing and risks breaking the game

The [issue](https://github.com/ValveSoftware/Proton/issues/5559#issuecomment-1058309456) is still not resolved and video playback still doesn't work. (GE-Proton8-25)
This patch resolves the video playback issue.

**Comment by DevSplash** [comment]
> Also, I looked into it a bit and in my playthrough, it didn't seem like there was any attempt to for a video to play. In the debug logs, there wasn't any error related to mfplat nor a missing plugin

You can try to run it on Windows, the video will be played normally. 

> it didn't seem like there was any attempt to for a video to play

That's right. Videos will be skiped if the patch is not applied.

**Comment by DevSplash** [comment]
> Don't know for sure if that's the cause though. @DevSplash were those the errors you were referring to?

I tried to look into it and found that this issue seems to be a common problem with TVP core (Kirikiri/Kirikiri 2/Kirikiri Z, etc.). 
The video format for this game is wmv, and it seems that the lack of a decoder is causing the playback issue.

**Comment by GloriousEggroll** [comment]
if it's verified working upstream then it should be working here. we need to figure out how to properly fix this in ge rather than work around it if it's already working properly upstream

**Comment by DevSplash** [comment]
> if it's verified working upstream then it should be working here. we need to figure out how to properly fix this in ge rather than work around it if it's already working properly upstream

Actually, this problem also exists when using the official Proton. (It has been incorrectly marked as verified.)

**Comment by GloriousEggroll** [comment]
Is there any part in the demo that has videos that have a problem? I tried the demo but couldnt find any issue

**Comment by DevSplash** [comment]
> Is there any part in the demo that has videos that have a problem? I tried the demo but couldnt find any issue

You can see the video when you play on Windows. 
Put the save file in `userdata\(your steam id)\1263470\remote` (unzip it first)
[datasu.zip](https://github.com/GloriousEggroll/protonfixes/files/13869082/datasu.zip)

**Pull request merged**
