### PR TITLE
Bejeweled 3 and Sonic CD fixes

### PR DESCRIPTION
**Pull request by spacecowgirl314**
The game doesn't work without disabling dxvk.

https://www.protondb.com/app/78000#BtH_f9uKxq

### CODE REVIEW

**Comment by spacecowgirl314** [comment]
Added another fix for Sonic CD. Uses some proton tricks found on https://www.protondb.com/app/200940. The video setup doesn't require dotnet40, I tested it. Framerate is locked to 60 fps because it speeds up the game where it shouldn't, it's mentioned on the top of https://www.pcgamingwiki.com/wiki/Sonic_CD_(2012). So a fix is needed even on Windows for people with 60+Hz monitors.

**Comment by GloriousEggroll** [comment]
wrt bejeweled 3:  generally any dx9/10/11 game should work with dxvk, and if not should be reported to dxvk's issue tracker. A quick check into the proton log for it shows it just needs d3dcompiler_43. I tested WINEDLLOVERRIDES=d3dcompiler_43=n and it loaded with dxvk perfectly fine.

I've gone ahead and merged the request but modified the bejeweled 3 protonfix to install d3dcompiler_43 instead of disabling dxvk. The sonic cd protonfix is fine, thanks for the fixes!

**Comment by GloriousEggroll** [comment]
Hmm ,something very odd is up with this game. WINEDLLOVERRIDES=d3dcompiler_43=n works, but installing d3dcompiler_43 via protonfixes does not. My assumption is the game does not like the d3dcompiler_43 version provided by winetricks. Adding the mentioned override without winetricks actually adding the DLL results in
```
54269.259:010c:0110:err:module:import_dll Library d3dcompiler_43.dll (which is needed by L"C:\\windows\\system32\\d3d10.dll") not found
```

However the game launches. Still digging into it to try to see whats up.

**Comment by GloriousEggroll** [comment]
Game has some weird issue with dx10 and d3dcompiler_43. PROTON_NO_D3D10=1 allows it to run in dx9 mode with dxvk. This is a far better solution than completely disabling dxvk.

**Pull request merged**
