### PR TITLE
util: use older winetricks for Proton 5.0

### PR DESCRIPTION
**Pull request by skryvel**
So. Well. For some reason during Proton 5.0 invocations `winecfg` 's window keeps popping up and things don't work. Without patience to investigate I reasoned it'd be about the updated `winetricks` and tried this. Seems to work, however ugly of a solution it may be.

Tested on GE 8-13 and Assetto Corsa

### CODE REVIEW

**Comment by GloriousEggroll** [comment]
this change replaces the default winetricks with the older one. it would affect all proton versions, not just proton 5. additional changes need to be made so that it only affects proton 5, not standard proton

**Comment by GloriousEggroll** [comment]
There is already a protontricks_proton_5 defined here:

https://github.com/GloriousEggroll/protonfixes/blob/aadfe42568b1c3271e1af4b835a6980719d05b7b/util.py#L295C1-L295C33

The proper approach would be to modify this instead to use the older winetricks for proton 5 and call it for games that need proton 5.

**Comment by skryvel** [comment]
No no, it sounds like that but see https://github.com/GloriousEggroll/protonfixes/pull/141/files#diff-367bda86ea6f92f7d469cb5d45eb7962078f35a5b2662e7ff5b206bcd0557b60R327. We're adding a 'new' executable (`winetricks_proton5`) which is just the old one with a comment about why, and then we invoke that one instead just for `protontricks_proton_5`

**Comment by GloriousEggroll** [comment]
aff im sorry you're right, i didn't see the def line of the function being edited. my bad and thanks for the fix!

**Pull request merged**
