### PR TITLE
Added support for Super naughty maid 2

### PR DESCRIPTION
**Pull request by Marc-Pierre-Barbier**
I already submitted this to the main Protonfixes repository, but seeing the differences between this version and Simon's i though I should also send the patch here.

### CODE REVIEW

**Comment by THMonster** [comment]
Blackscreen as before. Does it need any additional operation?
Log here:
[steam-1097880.log](https://github.com/GloriousEggroll/protonfixes/files/9265494/steam-1097880.log)

**Comment by Marc-Pierre-Barbier** [comment]
Since it's a video only app make sure make sure you have followed https://wiki.archlinux.org/title/wine#Other_dependencies

can you delete the game's prefix and then try again ?

if it's not fixed after that can you try with this version of the script ? https://raw.githubusercontent.com/Marc-Pierre-Barbier/protonfixes/24c7b03f94f99a7d73615f8fd66e9acd00a57a11/gamefixes/1097880.py 

i explicitly set windows xp but it shouldn't be needed

**Comment by THMonster** [comment]
What I have tried:
1. Check the deps that you mentioned: lib32-gst-plugins-base(installed), lib32-gst-plugins-good,(installed), lib32-gst-plugins-bad(install failed due to unresolvable dependencies),  lib32-gst-plugins-ugly(installed)
2. Delete game's prefix for a clean start
3. replace `~/.steam/steam/compatibilitytools.d/GE-Proton7-28/protonfixes/gamefixes/1097880.py` with the script that you provided
4. Start game from steam

But it still blackscreen, nothing changed,

**Comment by Marc-Pierre-Barbier** [comment]
what strange about your logs is that it looks like wmp9 is not even taken into account.

maybe you will have more luck with wmp11
delete the prefix before testing since i would expect wmp9 & 10 to be conflicting

 ```
""" Game fix for Super Naughty Maid 2
"""

from protonfixes import util


def main():
    """ installs quartz, wmp9
    """

    util.use_win32_prefix()

    # The whole game is only videos and require wmp9 & quartz
    util.protontricks('winxp')
    util.protontricks('quartz')
    util.protontricks('wmp11')
    util.protontricks('wmp9vcm')

```

**Comment by THMonster** [comment]
I found that the protonfix didn't take effect from the beginning.
`util.use_win32_prefix()`, but the prefix is still win64:
image

**Comment by THMonster** [comment]
Someone told me that proton-ge does not support `util.use_win32_prefix()`.
Did you test this script in proton-ge?

**Comment by THMonster** [comment]
And after deleting `util.use_win32_prefix()` , the rest code of this script can finally be executed normally.

**Comment by GloriousEggroll** [comment]
blah i missed use_win32_prefix -- we dont use that, and we dont use normal wmp9

instead try this please:

```

""" Game fix for Super Naughty Maid 2
"""

from protonfixes import util


def main():
    """ installs quartz, wmp9
    """

    # The whole game is only videos and require wmp9 & quartz
    util.protontricks('quartz')
    util.protontricks('wmp9_ge')
 ```

**Comment by Marc-Pierre-Barbier** [comment]
ok nice i just submitted what i had made for the original protonfixes so i missed this difference.

**Comment by GloriousEggroll** [comment]
can someone please 

> blah i missed use_win32_prefix -- we dont use that, and we dont use normal wmp9
> 
> instead try this please:
> 
> ```
> 
> """ Game fix for Super Naughty Maid 2
> """
> 
> from protonfixes import util
> 
> 
> def main():
>     """ installs quartz, wmp9
>     """
> 
>     # The whole game is only videos and require wmp9 & quartz
>     util.protontricks('quartz')
>     util.protontricks('wmp9_ge')
> ```
> 
> wmp9_ge allows installing wmp9 32 bit dlls properly into a 64 bit prefix:
> 
> https://github.com/GloriousEggroll/protonfixes/blob/master/gamefixes/verbs/wmp9_ge.verb

can someone please try this on a clean prefix to confirm?

**Comment by THMonster** [comment]
> can someone please
> 
> > blah i missed use_win32_prefix -- we dont use that, and we dont use normal wmp9
> > instead try this please:
> > ```
> > 
> > """ Game fix for Super Naughty Maid 2
> > """
> > 
> > from protonfixes import util
> > 
> > 
> > def main():
> >     """ installs quartz, wmp9
> >     """
> > 
> >     # The whole game is only videos and require wmp9 & quartz
> >     util.protontricks('quartz')
> >     util.protontricks('wmp9_ge')
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > wmp9_ge allows installing wmp9 32 bit dlls properly into a 64 bit prefix:
> > https://github.com/GloriousEggroll/protonfixes/blob/master/gamefixes/verbs/wmp9_ge.verb
> 
> can someone please try this on a clean prefix to confirm?

I have tried this, not work still blackscreen.
And a 32bit prefix (original wine) with quartz and wmp10 can running this game successfully. Maybe 32bit prefix is the key.

**Comment by THMonster** [comment]
I also tried 64bit prefix(original wine) with quartz and wmp11(cause wmp10 does not support 64bit prefix), it just get a fatal error after starting the game.

**Comment by GloriousEggroll** [comment]
if wmp10 works in 32 bit we need to make a new verb like the wmp9_ge verb. you do not need a 32 bit prefix. you just need the verb to install 32 bit dlls into syswow64 folder instead of system32 folder in the default 64 bit prefix.

**Pull request merged**
